<?php
/** Local-only editorial design fixture. Never create WordPress posts from this data. */

function voxa_media_design_preview_content() {
	return [
		'total' => 24,
		'featured' => [
			'title' => 'Kiến trúc tổng hợp tiếng nói thời gian thực với độ trễ dưới 50ms trên Edge Devices',
			'category' => 'Công nghệ Giọng nói',
			'category_slug' => 'voice',
			'author' => 'TS. Lê Quang Long',
			'date' => '22 Tháng 09, 2026',
			'datetime' => '2026-09-22',
			'excerpt' => 'Phân tích giải pháp tối ưu hóa pipeline ASR và TTS thế hệ mới của VOXA, giảm thiểu tài nguyên tiêu thụ và duy trì độ tự nhiên cao của âm sắc tiếng Việt.',
			'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuA4ljQfC9V2ru49E8QrKKGNLrKv5vxa_Nsx_X1OfVURlCgu5X0byfauTcfmgdaT-zop0ewcSaD1u97ZwQP08mxQ2RbLjw4nP-YgKH1jNb8ne8zNwpac7l0WwhYWcqD6f8aFUY8zxEuWBXfqeLJGO2aKc_EB0xvRgJx9bo2Ma4i-ibQ9lVnbMKW4f3Fv-ODPZuvjxpIZqjEXCcnhWXLAmczCNwahv5sDgR3tm_Ned0Wfo6r1Q_xoYAUX',
			'image_alt' => 'Abstract dark soundwave architecture visualization with electric-blue frequency lines',
		],
		'articles' => [
			[
				'title' => 'Đồng bộ hóa luồng Audio Streaming qua WebSocket cho ứng dụng Callbot',
				'category' => 'Xử lý Tín hiệu Âm thanh',
				'category_slug' => 'dsp',
				'author' => 'Kỹ thuật Viên',
				'date' => '19 Tháng 09, 2026',
				'datetime' => '2026-09-19',
				'excerpt' => 'Mô hình truyền dẫn full-duplex giảm packet jitter, kết hợp buffer xử lý gói tin thích ứng giúp tổng đài thoại thông minh phản hồi người dùng tức thì.',
				'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCMzzfYglZpbegzokuBlO7EES2ZsBFyRYB1SAIR7taqPMruwjSKAaVaMKvjv16Uk4L6eBIyia1S9WlnhX_DhDtGfXHbQFBjkEll8KuQFlYvxR68McN1r6ODGyD79SFzZC-FDqXNrQWgor8dY11kj-7uf_g4AitUJ0Lk-8wvRQvW8_6q-SH6dK6sj9yQRcu48ImojgJrgc8leUsHABQgqrbcIURA7bnvNw9bhQ_E8VQHuhuNLJuvQghD',
				'image_alt' => 'Digital audio-streaming waveform matrix on a dark server-room display',
			],
			[
				'title' => 'Xử lý chuẩn hóa từ vựng viết tắt và từ địa phương trong mô hình TTS tiếng Việt',
				'category' => 'Công nghệ Giọng nói',
				'category_slug' => 'voice',
				'author' => 'huong.linguist',
				'date' => '16 Tháng 09, 2026',
				'datetime' => '2026-09-16',
				'excerpt' => 'Phương pháp xây dựng từ điển phiên âm âm vị học mở rộng, kết hợp mô hình phân tích ngữ cảnh BERT để dự đoán trọng âm và cao độ thanh điệu.',
				'image' => '',
				'image_alt' => '',
			],
			[
				'title' => 'Đánh giá hiệu năng nén Opus 16kHz trong môi trường mạng di động chập chờn',
				'category' => 'Xử lý Tín hiệu Âm thanh',
				'category_slug' => 'dsp',
				'author' => 'audio_engineer_vn',
				'date' => '12 Tháng 09, 2026',
				'datetime' => '2026-09-12',
				'excerpt' => 'Khảo nghiệm thực địa tỷ lệ mất gói lên đến 30% trên mạng 4G/5G, phân tích thuật toán Forward Error Correction và khả năng phục hồi giọng nói tự nhiên.',
				'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBQnrHTxHD9l6iT8XrT6Nzk4kTYcQ_Ddxz1I6OFhj8BUlr3Vgkc920oKtzxQ_m9QNEVJ6tUxOGgncTGNOTIUF8ueryU_O6eeOQ1jzn37fJK0jZCgQaxPj08qt2ogHef30YY6MRE9gXtFzJ9ZMuFMs5GeBl4BQY_lw-YUq1cW-hNOg_2fgX7iCCX48vqKX7DNQqQIgI47smWNVLo8HpY4136ebfahtQqxvF81vNRBR8D88YXfo94XyJb',
				'image_alt' => 'Cellular transmission towers at dusk with audio waveform telemetry',
			],
			[
				'title' => 'Hướng dẫn cấu hình Webhook và xác thực HMAC trên VOXA REST API',
				'category' => 'Kiến trúc Hệ thống',
				'category_slug' => 'architecture',
				'author' => 'dev_danang',
				'date' => '08 Tháng 09, 2026',
				'datetime' => '2026-09-08',
				'excerpt' => 'Tích hợp thông báo bất đồng bộ khi hoàn tất tác vụ nhận dạng giọng nói tự động (ASR), bảo mật payload qua khóa ký số SHA-256 đối xứng.',
				'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuDKlRpzdwrtGpy5kAwJoSP9OxvC_aco-2I3lxZrF1rAn799Tc3v4M8BZbT4IhaPqnQjaz9sDFJppUPgWR7Kq173bB_NHHTj1noPIfIQznBgchw2k-8u5nrRIYYwTAbLIHRy-Pzd768Vse7m1PZrrAUML-Qpq-k6ixpSZDrUlGR50wNgl-fFRYbXMrNLINnxHvVPeiKIRfxp0e0enl4rRwLBqXW9GzQf6N1HnqIwJ5fYg-xYECh6jfLL',
				'image_alt' => 'Dark code editor showing webhook authentication and encrypted tokens',
			],
			[
				'title' => 'Bảo trì nâng cấp hạ tầng cụm máy chủ khu vực Đông Nam Á v2.6.9',
				'category' => 'Tin tức Sản phẩm',
				'category_slug' => 'news',
				'author' => 'Quản trị viên',
				'date' => '04 Tháng 09, 2026',
				'datetime' => '2026-09-04',
				'excerpt' => 'Báo cáo tiến trình di dời máy chủ GPU inference, triển khai cơ chế cân bằng tải tự động Anycast giúp giảm độ trễ khu vực miền Trung xuống 8ms.',
				'image' => '',
				'image_alt' => '',
			],
			[
				'title' => 'Nghiên cứu bộ chuyển đổi âm học FastSpeech 2 kết hợp vocoder HiFi-GAN',
				'category' => 'Công nghệ Giọng nói',
				'category_slug' => 'voice',
				'author' => 'Ban Biên Tập VOXA',
				'date' => '28 Tháng 08, 2026',
				'datetime' => '2026-08-28',
				'excerpt' => 'Tối ưu hóa khả năng điều chỉnh cao độ, trường độ và năng lượng ngữ điệu trong bài toán chuyển văn bản thành giọng nói thời gian thực chất lượng cao.',
				'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuDYlDxzF-fFzecJ70wA5wqMUrUzdRWjQzhPjjILJffQOV5SJy5SzBLzwAs1fNY92crn4BKzJ3HXyVn2LjAX1blquGZ0dePE3ec15I2x511mTuOWTkzQ-Q86kqpC9oHN1OuiMjlwvy8yYJ0rN07glFOw5tvgG9a1sCrgjnGLa8TbjxrTPeGyD9_md_0H5AqGKKjIHlYDfuJ8a9k1odhmPTXuehJ93FPqnMQfo_SpDF7cst88obyLlZ7G',
				'image_alt' => 'Neural-network nodes and tensor-flow diagram for speech synthesis',
			],
		],
	];
}
